### ISSUE TITLE
Investigate porting 'pdk validate' to golang

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/devx#16]
- Pick one external validator to POC using golang for validate
  - [x]  Execute rubocop check
  - [x] Hook up a PR showing validate of 2 example files demonstrating pass/fail

- Pick one internal ruby validator to POC using golang for validate
  - [x] Execute JSON syntax check
  - [x] Hook up a PR showing validate of 2 example files demonstrating pass/fail

**Comment by jpogran** [comment]
- [ ] Research how much of the validate feature could be ported to golang

**Comment by sanfrancrisko** [comment]
More detailed write up of PoC Phase I findings here: https://confluence.puppetlabs.com/display/ECO/PDK+Validate+PoC

**Comment by sanfrancrisko** [comment]
There was a rough PoC generated here: https://github.com/sanfrancrisko/pdkgo/tree/pdk-validate

With thanks to @da-ar , a more tidied up version that has a better project structure and better unit test conventions is up here: https://github.com/sanfrancrisko/pdkgo/tree/pdk-validate-mocked

There is a 3rd branch which is hoping to combine an:
- End to end `pdk validate ruby` command
- An example of a structure that is conducive to writing better unit tests in Go that can act as a conversation catalyst.

This is unfortunately in still a partially complete state and had to be parked due to the PCT LA release we are aiming for.

There is probably only 1 more day worth of work required, which I will aim to try and complete before we resume this work, in future.
